// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ayxnwhbbazrbrvratjvt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF5eG53aGJiYXpyYnJ2cmF0anZ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyMzI5MTksImV4cCI6MjA2NTgwODkxOX0.Mr-gCPWrHibPrJX9GBHqEbeaXls5mCLfCNxCJ1HsPMA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);